# Generated by Django 4.1.4 on 2023-01-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='First_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='Last_name',
            field=models.CharField(max_length=15),
        ),
    ]
